# Generated by Django 4.1.7 on 2023-03-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0002_deliveryman_user_key_alter_deliveryman_created'),
        ('order', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryapp.deliveryman'),
        ),
    ]
